### PR TITLE
add style index organ.html

### PR DESCRIPTION
**Pull request by RoyKoh**
@cbas

did some styling

### CODE REVIEW

**Comment by sebdeckers** [comment]
screen shot 2016-02-01 at 3 40 19 pm

**Comment by sebdeckers** [comment]
I can't easily find the code you want me to review because the commit includes lots of dependencies.

Dependency managers like NPM or Bower help avoid this problem. They let you `.gitignore` the dependency files so they don't pollute these PR diffs.

**Comment by sebdeckers** [comment]
# Step 1: Find the package on Bower or NPM

Bower:
http://bower.io/search/?q=FlexSlider

NPM:
https://npmsearch.com/?q=FlexSlider

_What if the package does not exist?_
1. Either publish it yourself onto Bower/NPM, or
2. Skip to find an alternative substitute package.

# Step 2: Deployment Automation

Create a `package.json` file with the necessary steps in the `scripts` section to retrieve the dependencies during installation.

## NPM

Always use `npm install --save` or `npm install --save-dev` so that packages are added (with the correct version) to the `dependencies` and `devDependencies` respectively. They will be installed automatically by `npm install` during deployment.

## Bower

Create a `bower.json` file automatically by saving the dependencies during installation.

See: http://bower.io/#save-packages

Then add a `postinstall` script to install the Bower dependencies after `npm install` completes successfully.

``` json
{
  "scripts": {
    "postinstall": "bower install"
  }
}
```

# Step 3: Web Server Configuration

Make sure the `bower_components` and `node_modules` folders are accessible from your web server.

Use [`http-server`](https://www.npmjs.com/package/http-server) to serve the root, or write a custom `server.js` file using Express and the static middleware to explicitly serve those folders.

**Comment by sebdeckers** [comment]
@sevresbabylone Could you please give @RoyKoh a hand with this mini-tutorial for Bower & NPM tomorrow? Feel free to call on @zellwk or myself if you have any questions.

**Comment by RoyKoh** [comment]
Noted

**Pull request merged**
